name: Deploy to GitHub Pages # Name of the workflow

on: # Triggers for the workflow
  push:
    branches:
      - src # Trigger when changes are pushed to the src branch

jobs: # Defines the jobs to run
  build-and-deploy: # Name of the job
    runs-on: ubuntu-latest # Specifies the operating system for the job

    steps: # Defines the steps within the job
      - name: Checkout code
        uses: actions/checkout@v3 # Checks out the code from the repository

      - name: Setup Node.js
        uses: actions/setup-node@v3 # Sets up Node.js
        with:
          node-version: '18' # Specifies the Node.js version

      - name: Install dependencies
        run: npm install # Installs the project dependencies

      - name: Build 11ty site
        run: npm run build # Builds the 11ty site

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3 # Deploys the built site to GitHub Pages
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }} # Uses the GitHub Actions token
          publish_dir: ./_site # Specifies the directory to deploy
          destination_folder: . #deploy to the root of the build branch.
          publish_branch: build # Specifies the branch to deploy to
          cname: presidentpedro.com #tells github pages to use the cname file.